# Generated by Django 4.2 on 2023-11-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='car_type',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
