# Generated by Django 4.2 on 2023-11-15 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postimages', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='PostImages'),
        ),
    ]
